---
driver:
  name: vagrant
  require_chef_omnibus: 12.18.31

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-6.7

suites:
  - name: package
    run_list:
      - recipe[ruby_installer::default]
    attributes:
      ruby_installer:
        method: package

  - name: source
    run_list:
      - recipe[ruby_installer::default]
    attributes:
      ruby_installer:
        method: source

  - name: ree
    run_list:
      - recipe[ruby_installer::default]
    attributes:
      ruby_installer:
        method: ree
