---
driver:
  name: vagrant
  require_chef_omnibus: 12.18.31

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-6

suites:
  - name: default
    run_list:
      - recipe[ruby_installer::default]
    attributes:
